cursor            #47FF9C
cursor_text_color #011423

foreground            #CBE0F0
background            #00111E
selection_foreground  #CBE0F0
selection_background  #033259
url_color             #033259

color0 #214969
color1 #E52E2E
color2 #44FFB1
color3 #FFE073
color4 #0FC5ED
color5 #a277ff
color6 #24EAF7
color7 #24EAF7

color8 #214969
color9 #E52E2E
color10 #44FFB1
color11 #FFE073
color12 #A277FF
color13 #a277ff
color14 #24EAF7
color15 #24EAF7

mark1_foreground #002201
mark1_background #bff0b1
mark2_foreground #111f0f
mark2_background #d6e8cd
mark3_foreground #002022
mark3_background #bcebef

active_tab_foreground #0e380d
active_tab_background #a3d397
inactive_tab_foreground #bff0b1
inactive_tab_background #265022

active_border_color #a3d397
inactive_border_color #0e380d
