cursor            #aec6ff
cursor_text_color #122f60

foreground            #e2e2e9
background            #0c0e13
selection_foreground  #293041
selection_background  #bfc6dc
url_color             #bfc6dc

#: black 000000 767676
color0  #121318
color8  #33353a
#: red cc0403 f2201f
color1  #73405b
color9  #bf8da7
#: green 19cb00 23fd00
color2  #bfc6dc
color10 #dbe2f9
#: yellow cecb00 fffd00
color3  #dfbbde
color11 #fcd7fb
#: blue 0d73cc 1a8fff
color4  #2c4678
color12 #aec6ff
#: magenta cb1ed1 fd28ff
color5  #3f4759
color13 #bfc6dc
#: cyan 0dcdcd 14ffff
color6  #583e5a
color14 #dfbbde
#: white dddddd ffffff
color7  #c5c6d0
color15 #e2e2e9

mark1_foreground #001a43
mark1_background #d8e2ff
mark2_foreground #141b2c
mark2_background #dbe2f9
mark3_foreground #2a132d
mark3_background #fcd7fb

active_tab_foreground #122f60
active_tab_background #aec6ff
inactive_tab_foreground #d8e2ff
inactive_tab_background #2c4678

active_border_color #aec6ff
inactive_border_color #122f60
