cursor #e0e4da
cursor_text_color #c2c8bc

foreground            #e0e4da
background            #11140f
selection_foreground  #263422
selection_background  #baccb2
url_color             #a3d397

color0   #11140f
color1   #f28a6d
color2   #6dd369
color3   #ffed72
color4   #91c884
color5   #38612e
color6   #a3d397
color7   #d2ddd0
color8   #80897e
color9   #ffb49f
color10  #a7fda4
color11  #fff4a5
color12  #bbe8b0
color13  #d6ffcc
color14  #e4ffde
color15  #f9fff8
