#!/bin/sh

bspc monitor -d 1 2 3 4 5
# bspc monitor -d    ﭮ   

bspc config normal_border_color \#1e1e1e
bspc config focused_border_color \#7aa2f7
bspc config border_width         2
bspc config window_gap          5
bspc config focus_follows_pointer true
# bspc config bottom_padding -10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config single_monocle       true
bspc config gapless_monocle      false

# bspc config pointer_motion_interval 1

# polybar &
picom &
xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144 --right-of HDMI-A-0 &
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 75 --left-of DisplayPort-0 &
xwallpaper --center ~/nixos-dotfiles/walls/leaves.png
sxhkd &
# feh --bg-tile ~/wallpapers/kanagawa.jpg &
